name: Deployment

on:
  push:
    branches:
      - main

jobs:
  Test:
    name: Testing again to make sure changes from master didnt break anything
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: graalvm-ce-java11@21.1.0

      - name: Run tests
        run: sbt test
  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build artifact
        run: sbt clean assembly

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: narrative-analytics.jar
          path: target/scala-3.1.1/narrative-analytics.jar

  Publish:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: narrative-analytics.jar

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/analytics:latest
